image: node:latest

pages:
  stage: deploy
  script:
    - yarn
    - yarn prod
    - pwd
    - ls
    - echo "I am on gitlab-runner"
    - cp -rp dist public_html
  artifacts:
    paths:
      - public_html
  only:
    - master
